config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'
  
  get 'posts/myindex'

  get 'posts/ourindex'
  
  
  post '/posts/create' => 'posts#create' 
  post '/posts/myindex' => 'posts#myindex'

  get 'home/index'
  get 'home/weather'
  get 'home/setting'
  
  resources 'posts' do
    post "/like", to: "likes#like_toggle"
  
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
    
    mount_uploader :image, ImageUploader
    
    belongs_to :user
    has_many :likes
    has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :check_ownership, only: [:edit, :update, :destroy]
  
  def ourindex
    @posts = Post.all.order('created_at desc') 
  end
  
  def myindex
    @posts = current_user.posts.reverse #현재 사용자의 게시글을 모두 가져온다.
  end
  
  def create
    new_post = Post.new(user_id: current_user.id, content: params[:content], outer: params[:outer], top: params[:top], bottom: params[:bottom], dress: params[:dress], etc: params[:etc])

    new_post.image = params[:image]

    privacy = params[:show_attribute]
    
    if privacy == "1"
      new_post.show_attribute = true
    else
      new_post.show_attribute = false
    end
    
    if new_post.save
      redirect_to '/posts/myindex'
    else
      redirect_to '/posts/myindex'
    end
  end

  def edit
    #@post = Post.find_by(id: params[:id])
  end

  def update
    #@post = Post.find_by(id: params[:id])
    redirect_to root_path if @post.user.id != current_user.id
    
    @post.image = params[:image] unless params[:image].nil?
    
    @post.update_attributes(content: params[:content], outer: params[:outer], top: params[:top], bottom: params[:bottom], dress: params[:dress], etc: params[:etc])
    privacy = params[:show_attribute]
    
    if privacy == "1"
      @post.show_attribute = true
    else
      @post.show_attribute = false
    end
    
    if @post.save
      redirect_to post_path
    else
      render :edit
    end
  end
  
  def show
    @post = Post.find_by(id: params[:id])
  end

  def destroy
    @post.destroy
    redirect_to '/posts/myindex'
  end
  
  def check_ownership 
    @post = Post.find_by(id: params[:id]) 
    redirect_to root_path if @post.user.id != current_user.id 
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container">
    <%= form_tag post_path(@post), method: "patch", multipart: true do %>
              
        <div class="row justify-content-end">
          <p> OPEN ? &nbsp;&nbsp;</p> 
          <label class="switch">
            <input type="checkbox" checked>
            <span class="slider round"></span>
          </label>
        </div>
        
        <!--new-->
        <%#= form_tag posts_path, method: 'post' do %>
        <%#= text_field_tag 'title' %>
        <%#= text_area_tag 'content' %>
        <%#= submit_tag 'Submit!' %>
        <%# end %>
        
        
        <!--edit-->
        <%#= form_tag post_path(@post.id), method: 'patch' do %>
        <%#= text_field_tag 'title', @post.title %>
        <%#= text_area_tag 'content', @post.content %>
        <%#= submit_tag 'Submit!' %>
        <%# end %>
        
        
        
        <p> DATE&nbsp;&nbsp;:&nbsp;&nbsp;
            <%= date_field_tag 'input_date', nil %>
            
        </p> PHOTO&nbsp;:&nbsp;
        
             <%= file_field_tag 'image', accept: 'image/*'  %>
            <br> <br>
        
        <p> Comment</p>    
        <p>
          <%= text_area_tag 'content', @post.content, style: "width: 100%", rows: 5 %>
        </p>
        <hr>
        <p> OUTER :
          <%= text_field_tag 'outer', @post.outer, style: "width: 33%" %>
        </p>
        <p> TOP   :
          <%= text_field_tag 'top', @post.top, style: "width: 33%" %>
        </p>
        <p> BOTTOM :
          <%= text_field_tag 'bottom', @post.bottom, style: "width: 33%" %>
        </p>
        <p> DRESS  :
          <%= text_field_tag 'dress', @post.dress, style: "width: 33%" %>
        </p>
        <p> ETC    :
          <%= text_field_tag 'etc', @post.etc, style: "width: 33%" %>
        </p>
        <p><%= check_box_tag(:show_attribute) %>
                    <%= label_tag(:show_attribute, "공개할거임?") %></p>
        <%= submit_tag '수정하기'%>
    <% end %>
</div>

app/views/posts/myindex.html.erb
  <head>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/mypage.css" >
    <!--<title>My Closet</title>-->
  </head>
  <body>
    <div class="container">
      <!--Profile-->
      <!-- user info -->
      <section class="user profile">
      <div class="py-3 row">
        <div class="col-12 col-lg-6 offset-xl-2 col-xl-4 d-flex flex-row">
          <div class="col-3 d-flex flex-column justify-content-center">
            <p></p>
                            <a class="ml-1" href="">
                  <img src="" style="width: 15px; height: 15px"></a>
          </div>
          <div class="col-9 d-flex flex-column justify-content-center">
            <span class="mb-1"><%= current_user.name %>
                <a class="ml-1" href="/home/setting">
                  <i class="fa fa-cog" aria-hidden="true"></i></a>
            </span>
            <span class="mb-1">
            </span>
            <span class="small mb-1 font-weight-light">거주지역 :</span>  <!--current_user.region-->
            <span class="small mb-1">스타일 : </span>
          </div>
        </div>
      </div>
      </section>
    <!-- 내 옷장 사진들 -->
    <div class="row">
          <div class="col-12">
            <br>
            <h4>My Closet</h4> <br>
            <hr>
          </div>
    </div>
    
   <div class="row justify-content-end">
      <!--<div class="col-sm-11"></div>-->
      <div class="col-2">
          <!-- Button trigger modal -->
          <button class="btn btn-outline-primary" data-target="#layerpop" data-toggle="modal">Upload</button>
      </div>
    </div>
    <br>
    
    
     <!--나중에는 루비 반복문으로 돌려야함 -->
    <div class="row mb-5 no-gutters">
        <% @posts.each do |post| %>
          <div class="col-sm-4 mt-4 clst">
                  
                     <p> <%= post.id %></p>
                     <% if post.image.url.nil? %>
                       <%= image_tag("logo_.png") %>
                     <% else %>
                       <a href = "/posts/<%=post.id%>">
                     <%= image_tag post.image.url, :class => "upload-img"%>
                     <!--<div class="overlay">-->
                     <!-- <div class="text justify-content-center">-->
                     <!--   <i class="like fa fa-heart"></i>-->
                     <!--   <i class="comment fa fa-commenting-o"></i>-->
                     <!-- </div>-->
                     <!-- </div>-->
                      </a>
                     <% end %>
                    
                  
          </div>
       <% end %>
    </div>

    <!--<div class="row mb-5 no-gutters">-->
    <!--  <div class="col-sm-4 clst">-->
    <!--    <a href = "/posts/show">-->
    <!--    <img class="upload-img" src="/assets/photo1.jpg" alt="업로드 사진" >-->
    <!--    <div class="overlay">-->
    <!--      <div class="text justify-content-center">-->
    <!--        <i class="like fa fa-heart"></i>-->
    <!--        <i class="comment fa fa-commenting-o"></i>-->
    <!--      </div>-->
    <!--  </div>-->
    <!--  </a>-->
    <!--  </div>-->
    <!--  <div class="col-4 clst">-->
    <!--    <img class="upload-img" src="/assets/photo2.jpg" alt="업로드 사진" >-->
    <!--    <div class="overlay">-->
    <!--      <div class="text justify-content-center">-->
    <!--        <i class="like fa fa-heart"></i>-->
    <!--        <i class="comment fa fa-commenting-o"></i>-->
    <!--      </div>-->
    <!--  </div>-->
    <!--  </div>-->
    <!--  <div class="col-4 clst">-->
    <!--    <img class="upload-img" src="/assets/photo3.jpg" alt="업로드 사진" >-->
    <!--    <div class="overlay">-->
    <!--      <div class="text justify-content-center">-->
    <!--        <i class="like fa fa-heart"></i>-->
    <!--        <i class="comment fa fa-commenting-o"></i>-->
    <!--      </div>-->
    <!--  </div>-->
    <!--</div>-->
    <!--</div>-->
    <!--<div class="row mb-5 no-gutters">-->
    <!--  <div class="col-4 clst">-->
    <!--    <img class="upload-img" src="/assets/photo4.jpg" alt="업로드 사진" >-->
    <!--    <div class="overlay">-->
    <!--      <div class="text justify-content-center">-->
    <!--        <i class="like fa fa-heart"></i>-->
    <!--        <i class="comment fa fa-commenting-o"></i>-->
    <!--      </div>-->
    <!--  </div>-->
    <!--  </div>-->
    <!--  <div class="col-4 clst">-->
    <!--    <img class="upload-img" src="/assets/photo5.jpg" alt="업로드 사진" >-->
    <!--    <div class="overlay">-->
    <!--      <div class="text justify-content-center">-->
    <!--        <i class="like fa fa-heart"></i>-->
    <!--        <i class="comment fa fa-commenting-o"></i>-->
    <!--      </div>-->
    <!--  </div>-->
    <!--  </div>-->
    <!--  <div class="col-4 clst">-->
    <!--    <img class="upload-img" src="/assets/photo6.jpg" alt="업로드 사진" >-->
    <!--    <div class="overlay">-->
    <!--      <div class="text justify-content-center">-->
    <!--        <i class="like fa fa-heart"></i>-->
    <!--        <i class="comment fa fa-commenting-o"></i>-->
    <!--      </div>-->
    <!--  </div>-->
    <!--</div>-->
    <!--</div>-->

    
    <!-- 글 작성  -->
    <!-- Modal -->
    <div class="modal fade" id="layerpop" >
    <div class="modal-dialog">
      <div class="modal-content">
        <!-- header -->
        <div class="modal-header">
          <!-- 닫기(x) 버튼 -->
          <button type="button" class="close" data-dismiss="modal">×</button>
          <!-- header title -->
          <h4 class="modal-title">+ New Closet</h4>
        </div>
        <!-- body -->
        <div class="modal-body mx-auto">
          <%= form_tag("/posts/create",  method: "post", multipart: true) do %>
            <!--<div class="row justify-content-end">-->
            <!--  <p> OPEN ? &nbsp;&nbsp;</p> -->
            <!--  <label class="switch">-->
            <!--    <input type="checkbox" checked>-->
            <!--    <span class="slider round"></span>-->
            <!--  </label>-->
            <!--</div>-->
            <!--<p> DATE&nbsp;&nbsp;:&nbsp;&nbsp;-->
            <!--    <%= date_field_tag 'input_date', nil %>-->
            </p> PHOTO&nbsp;:&nbsp;
                <%= file_field_tag 'image', accept: 'image/*' %><br> <br>
            <p> Content</p>    
            <p>
              <%= text_area_tag 'input_content', nil, style: "width: 100%", rows: 5 %>
            </p>
            <hr>
            <p> OUTER :
              <%= text_field_tag 'outer', nil, style: "width: 33%" %>
            </p>
            <p> TOP   :
              <%= text_field_tag 'top', nil, style: "width: 33%" %>
            </p>
            <p> BOTTOM :
              <%= text_field_tag 'bottom', nil, style: "width: 33%" %>
            </p>
            <p> DRESS  :
              <%= text_field_tag 'dress', nil, style: "width: 33%" %>
            </p>
            <p> ETC    :
              <%= text_field_tag 'etc', nil, style: "width: 33%" %>
            </p>
            <p><%= check_box_tag(:show_attribute) %>
              <%= label_tag(:show_attribute, "공개할거임?") %></p>
        </div>
        <!-- Footer -->
        <div class="modal-footer">
          <%= submit_tag 'Upload', :class=> "btn btn-primary"%>
          
          <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>
  </body>
  
  
  

app/views/posts/ourindex.html.erb
  <head>
    <link rel="stylesheet" href="css/ourpage.css" >
    
    <title>Our Closet</title>

  </head>
  <body>
    <div class="container">
      <!--We closet-->
      <div class="row">
            <div class="col-12">
              <br>
              <h4 class="text-center">Our Closet</h4> <br>
            </div>
      </div>
  <div class="row mb-5 no-gutters">      
      <% @posts.each do |post| %>
      <% if post.show_attribute == true %>
        

          
          <div class="col-4 mt-5 clst">
            <% if post.image.url.nil? %>
             <%= image_tag("logo_.png") %>
           <% else %>
             <%= image_tag post.image.url, :class => "upload-img"%>
           <% end %>
          <!--<img class="upload-img" src="" alt="업로드 사진" >-->
            <!--<div class="overlay">-->
            <!--  <div class="text justify-content-center">-->
            <!--    <i class="like fa fa-heart"></i>-->
            <!--    <i class="comment fa fa-commenting-o"></i>-->
              
            <!--  </div>-->
            <!--</div>-->
            <div class="row mt-2 justify-content-center">
              <% if post.likes.size == 0 %>
              <p><%= post.likes.size %> 명이 좋아합니다.</p>
              <% else %>
              <p><%= post.likes_count %> 명이 좋아합니다.</p>
              <% end %>
              
              <% if current_user.is_like?(post) %>
                    <%= link_to post_like_path(post), method: "post" do %>
                    <i class="heart fa fa-heart fa-2x"></i>
                  <% end %>
              <% else %>
                  <%= link_to post_like_path(post), method: "post" do %>
                  <i class="heart fa fa-heart-o fa-2x"></i>
                  <% end %>
              <% end %>
              <i class="star fa fa-star-o fa-2x"></i>
            </div>
          </div>
        
        <% end %>
        <% end %>
        </div>
      
  <!--    <div class="row mb-5 no-gutters">-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo1.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--        <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo2.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--        <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo3.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--       <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--  </div>-->
    
  <!--  <div class="row mb-5 no-gutters">-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo7.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--        <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo8.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--        <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo9.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--        <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--  </div>    -->
  <!--  <div class="row mb-5 no-gutters">-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo10.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--        <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo11.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--       <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--    <div class="col-4 clst">-->
  <!--      <img class="upload-img" src="/assets/photo12.jpg" alt="업로드 사진" >-->
  <!--      <div class="overlay">-->
  <!--        <div class="text justify-content-center">-->
  <!--          <i class="like fa fa-heart"></i>-->
  <!--          <i class="comment fa fa-commenting-o"></i>-->
  <!--        </div>-->
  <!--      </div>-->
  <!--      <div class="row mt-2 justify-content-center">-->
  <!--        <i class="heart fa fa-heart-o fa-2x"></i>-->
  <!--        <i class="star fa fa-star-o fa-2x"></i>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--  </div>-->
  <!--</div>-->
        
  </div>
  <script>
    $(".star.fa").click(function() {
      $(this).toggleClass("fa-star  fa-star-o");
    });
    
    $(".heart.fa").click(function() {
      $(this).toggleClass("fa-heart fa-heart-o");
    });

  </script>
  
  </body>

app/views/posts/show.html.erb
<head>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/show.css" >
    <title>My Closet</title>
</head>
<body>
<div class="container">
    <div class="row">
    <div class="col-6">
        <img class="show-img" src="<%= @post.image.url %>" alt="업로드 사진" >
    </div>
    <div class="col-6">
    <div class="row">
        
    <div class="col-4 d-flex flex-column">
            <div class="prof-img">
                <p>프로필사진</p>
            </div>
        </div>
    <div class="col-8 d-flex flex-column">
            <span class="mb-1"><%= current_user.name %> </span>
            <span class="small mb-1">거주지역 : </span>
            <span class="small mb-1">스타일 : </span>
           
    </div>
    </div>
    
    <p><%= @post.content %></p>
    <p>outer :<%= @post.outer %> </p>
    <p>top : <%= @post.top %></p>
    <p>bottom : <%= @post.bottom %></p>
    <p>dress : <%= @post.dress %></p>
    <p>etc : <%= @post.etc %></p>
    
    <div class="edit justify-content-end">
    <%= link_to edit_post_path do %>
    <i class="fa fa-pencil-square-o fa-2x mr-4" aria-hidden="true"></i>
    <% end %>
    
    <%= link_to post_path, method: :delete, data: { confirm: 'Are you sure?' } do %>
    <i class="fa fa-times fa-2x" aria-hidden="true"></i>
    <% end %>
        
    </div>
    <!--업로드할때 작성한 내용 출력-->
    
    </div>
    <!-- 댓글 창-->

    </div>
</div>
</body>